services:
  app:
    image: localhost:3000/lajuladotapp/lajula.app:0.0.8
    container_name: lajula.app
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true