services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    ports:
      - "3025:8025"   # web UI
      - "1025:1025"   # SMTP
    volumes:
      - mailpit-data:/data
    networks:
      - shared-network

volumes:
  mailpit-data:

networks:
  shared-network:
    external: true
