services:
  app:
    image: localhost:3000/lajuladotapp/lajuladotapp:latest
    container_name: lajuladotapp
    restart: unless-stopped
    ports:
      - "8200:80"
    networks:
      - shared-network

networks:
  shared-network:
    external: true